version: "3.9"
services:
  php-fpm:
    build:
      context: ./Docker/php
    container_name: php-fpm
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www"
    networks:
      - app
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - "./Docker/mysql/data:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=idus
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test123
    networks:
      - app
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./Docker/nginx/conf.d:/etc/nginx/conf.d"
      - "./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - app

networks:
  app:
    driver: bridge
